List
TMamaev/Task pull request #15
Opened 2024-05-28 18:31 UTC by TMamaev

Did func Length

2024-05-29 06:02 UTC, justas05 commented
И все?..

2024-07-12 10:57 UTC, justas05 commented on individual/list.c
> +int new_lst(t_list *head, int new)
Что делает эта функция?

2024-07-12 15:22 UTC, TMamaev commented on individual/list.c
> +int new_lst(t_list *head, int new)
Выделяет память под новый элемент списка

2024-07-18 06:53 UTC, justas05 requested changes

2024-07-18 06:53 UTC, justas05 commented on individual/list.c
> +    while (*lst->next != NULL)
А что будет, если список изначально пуст?

2024-07-31 06:34 UTC, justas05 requested changes
Нужно дальше проверять функции

2024-07-31 06:34 UTC, justas05 commented on individual/list.c
> +    del(lst);
del - это указатель на функцию. Какой может быть этот указатель?..

2024-07-31 06:34 UTC, justas05 commented on individual/list.c
> +        (*lst)->next = new;
Здесь надо подумать, что ты делаешь и зачем...

2024-08-19 06:05 UTC, justas05 reviewed
Задача проходит все тесты?

2024-09-09 05:24 UTC, justas05 requested changes

2024-09-09 05:24 UTC, justas05 commented on individual/list.c
> +void push(t_stack** head, int n)
Функция должна работать со стеком, а не списком.

2024-09-09 05:24 UTC, justas05 commented on individual/list.c
> +    size_t size = sizeof(s)/sizeof(char);
FYI: Так работает вычисление размера только для статических массивов.

2024-09-09 05:24 UTC, justas05 commented on individual/list.c
> +    for (int i = 0; i < size;)
Этот алгоритм гарантированно работать не будет.

2024-10-12 10:11 UTC, merged