Изменил все задачи с с++ на с
TMamaev/Task pull request #3
Opened 2023-10-31 20:02 UTC by TMamaev

Выполнил задание. Изменил команды cin cout на scanf printf. Перенес все из текстового файла

2023-11-01 08:26 UTC, justas05 requested changes
Это раздел "ввод-вывод"! В нем не требуется использования никаких конструкций кроме арифметики и ввода-вывода информации. Необходимо избавиться от циклов и условного оператора.

2023-11-01 08:26 UTC, justas05 commented on main.c
> +#include <limits.h>
Файл `main.c` не следует добавлять, т.к. он не относится к данному ПРу

2023-11-01 08:26 UTC, justas05 commented on informatics/language_learning/input_output.c
> +}
В конце файла делай пустую строку, иначе будет некорректное отображение, например, как здесь

2023-11-01 08:26 UTC, justas05 commented on informatics/language_learning/input_output.c
> +    int n, m;
Объявляй переменные по одной на строке.
После объявления переменных делай отступ в 1 строку.

2023-11-01 08:26 UTC, justas05 commented on informatics/language_learning/input_output.c
> +    int time1 = 540;
Пиши все объявления переменных в начале функции.

2023-11-01 08:26 UTC, justas05 commented on informatics/language_learning/input_output.c
> +    int h, m;
Переменные можно не создавать в принципе

2023-11-01 08:26 UTC, justas05 commented on informatics/language_learning/input_output.c
> +
Зачем так много отступов?

2023-11-01 08:26 UTC, justas05 commented on informatics/language_learning/input_output.c
> +    if (s<10)
Во-первых, отделяй знак пробелами, а, во-вторых, в этом разделе мы не пользуемся никакими конструкциями. В частности `if`. Почитай, как работает `printf` и сделай без условия.

2023-11-01 08:26 UTC, justas05 commented on informatics/language_learning/input_output.c
> +        for (; n > 3600;)
Зачем тут цикл? Подумай, что в нем происходит. Не нужно реализовывать самое тривиальное решение, которое первым пришло к тебе в голову.

2023-11-01 08:26 UTC, justas05 commented on informatics/language_learning/input_output.c
> +
Много пустых строк.
Отсутствует ссылка на задачу.

2023-11-02 19:59 UTC, justas05 requested changes

2023-11-02 19:59 UTC, justas05 commented on informatics/language_learning/input_output.c
> +    printf("%d", (v * t) % 109);
Не во всех случаях сработает.

2023-11-02 19:59 UTC, justas05 commented on informatics/language_learning/input_output.c
> +    printf("%d", n % 100 % 10);
А зачем находить остаток от деления на 100, если потом ищется остаток на 10?

2023-11-02 19:59 UTC, justas05 commented on informatics/language_learning/input_output.c
> +    printf("%d", (n - n % 10) / 10);
Что получится, если число разделить на 10, когда разряд единиц не равен нулю?

2023-11-02 19:59 UTC, justas05 commented on informatics/language_learning/input_output.c
> +    printf("%d", ((n - n % 10) % 100 / 10));
Аналогично предыдущему

2023-11-02 19:59 UTC, justas05 commented on informatics/language_learning/input_output.c
> +  printf("%d", n % 100 % 10 + ((n - n % 10) % 100 / 10) + ((n - n % 100) / 100) );
Посмотреть предыдущие комментарии и поправить...

2023-11-02 19:59 UTC, justas05 commented on informatics/language_learning/input_output.c
> +    printf("%d %d", n/60, n%60);
пробелы

2023-11-02 19:59 UTC, justas05 commented on informatics/language_learning/input_output.c
> +    ("%d%d:", 0 + (((n % 3600) / 60) / 10), (n % 3600) / 60);
что-то странное... Программа не скомпилируется

2023-11-02 19:59 UTC, justas05 commented on informatics/language_learning/input_output.c
> +    printf("%d %d", (540 + 5 * (les / 2 + les % 2) + (les / 2)) / 60, (540 + 5 * (les / 2 + les % 2) + (les / 2)) % 60);
выглядит очень сложно и нечитаемое

2023-11-02 19:59 UTC, justas05 commented on informatics/language_learning/input_output.c
> +
пустые строки здесь излишне

2023-11-03 15:23 UTC, TMamaev commented on informatics/language_learning/input_output.c
> +    printf("%d", (n - n % 10) / 10);
У меня для этого и сделана n - n % 10. На пример 87. 87 % 10 = 7 и я из 87 вычитаю 7

2023-11-03 15:35 UTC, justas05 commented on informatics/language_learning/input_output.c
> +    printf("%d", (n - n % 10) / 10);
Вопрос в том, что получится? Читай внимательно! Это очень важно!!!

2023-11-03 18:09 UTC, justas05 requested changes
Завтра досмотрим

2023-11-03 18:09 UTC, justas05 commented on informatics/language_learning/input_output.c
> +    n_without_1 = (n - n % 10);
Попробуй сделать 15 / 10 или 10/10, посмотреть, что получится и решить, есть ли здесь лишние действия.

2023-11-03 18:09 UTC, justas05 commented on informatics/language_learning/input_output.c
> +  int n;
Почему отступы стали разными?

2023-11-17 19:03 UTC, justas05 approved these changes

2023-11-18 09:21 UTC, closed without merging